### ISSUE TITLE
Adjustments

### ISSUE THREAD

**Issue by Kingjosh007** [Whoistolu/personal-portfolio#14]
## Hello [@Whoistolu](https://github.com/Whoistolu/)

Great job so far, however here is what could be improved or fixed: 

- When hovering on the modal buttons, they disappear, which isn't good for the UX
- The modal should not fully cover the screen on the mobile view

**Comment by Whoistolu** [comment]
## Hello  [@Kingjosh007 ](https://github.com/Kingjosh007)

Thank you for your feedback. I have fixed the issue.
